name: CFNScraper Pipeline
on:
  pull_request:
    branches: [ master ]
  push:
    branches: [ master, development ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v3
      - uses: n8maninger/action-golang-test@v1
        env:
          STEAM_USERNAME: ${{ secrets.STEAM_USERNAME }} 
          STEAM_PASSWORD: ${{ secrets.STEAM_PASSWORD }} 
          TESTING: 'true'